spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configuracion de Actuator
info.app.name=Eureka Server
info.app.description=Service Discovery Server
info.app.version=1.0.0
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
