spring.application.name=eureka-server
server.port=8761

eureka.client.register-with-eureka=${EUREKA_CLIENT_REGISTER_WITH_EUREKA}
eureka.client.fetch-registry=${EUREKA_CLIENT_FETCH_REGISTRY}

# Configuracion de Actuator
info.app.name=Eureka Server
info.app.description=Service Discovery Server
info.app.version=1.0.0
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/actuator
